# Generated by Django 6.0.5 on 2026-06-03 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_householdlist_householdlistitem_investmentgoal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='category',
            name='unique_personal_category',
            constraint=models.UniqueConstraint(condition=models.Q(('household__isnull', True)), fields=('user', 'name', 'type'), name='unique_personal_category', violation_error_message='Você já tem uma categoria com esse nome e tipo.'),
        ),
        migrations.AlterConstraint(
            model_name='category',
            name='unique_household_category',
            constraint=models.UniqueConstraint(condition=models.Q(('household__isnull', False)), fields=('household', 'name', 'type'), name='unique_household_category', violation_error_message='O grupo já tem uma categoria com esse nome e tipo.'),
        ),
    ]
