# Generated by Django 6.0.5 on 2026-06-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_category_unique_personal_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installment_group',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
