# Generated by Django 6.0.5 on 2026-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_recurringtransaction_transaction_recurring_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('debit_card', 'Cartão de débito'), ('credit_card', 'Cartão de crédito'), ('pix', 'Pix'), ('bank_slip', 'Boleto'), ('bank_transfer', 'Transferência')], default='cash', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('debit_card', 'Cartão de débito'), ('credit_card', 'Cartão de crédito'), ('pix', 'Pix'), ('bank_slip', 'Boleto'), ('bank_transfer', 'Transferência')], default='cash', max_length=15),
        ),
    ]
