# Generated by Django 6.0.5 on 2026-06-05 14:21

from django.db import migrations, models


def clear_legacy_icon_text(apps, schema_editor):
    # The icon field used to hold free text; those values are not valid image
    # paths, so blank them to avoid broken images after the switch.
    Category = apps.get_model('finances', 'Category')
    Category.objects.exclude(icon='').update(icon='')


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_alter_recurringtransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
        migrations.RunPython(clear_legacy_icon_text, migrations.RunPython.noop),
    ]
