# Generated by Django 6.0.5 on 2026-06-05 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#3498db', max_length=7, validators=[django.core.validators.RegexValidator(message='A cor deve ser um valor hexadecimal, ex.: #1abc9c.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='type',
            field=models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10),
        ),
    ]
