# Generated by Django 6.0.5 on 2026-06-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_alter_category_color_alter_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nature',
            field=models.CharField(choices=[('fixed', 'Fixa'), ('variable', 'Variável')], default='variable', max_length=10),
        ),
    ]
